name: Imagebuilder_Xiaomi_Mi_3A-Snapshot

# Add a button to trigger the workflow
on: 
  repository_dispatch:
  workflow_dispatch:

env:
  BOARD: "ramips"
  SUBTARGET: "mt76x8"
  PROFILE: "xiaomi_miwifi-3a"
  PACKAGES_TYPE1: "luci luci-theme-material luci-app-adblock tcpdump-mini -ip6tables -odhcp6c -kmod-ipv6 -kmod-ip6tables -odhcpd-ipv6only -ppp -ppp-mod-pppoe luci-app-https-dns-proxy curl openssh-sftp-server internet-detector luci-app-internet-detector luci-app-log-viewer" 
  # luci-app-access-control luci-app-cpu-status-mini    

  PACKAGES_TYPE2: "uhttpd luci-mod-admin-full luci-base libiwinfo-lua luci-app-firewall luci-theme-material -ip6tables -odhcp6c -kmod-ipv6 -kmod-ip6tables -odhcpd-ipv6only -ppp -ppp-mod-pppoe luci-app-https-dns-proxy -kmod-usb-ledtrig-usbport -kmod-usb-ohci -kmod-usb2 -opkg luci-app-adblock internet-detector luci-app-internet-detector luci-app-log-viewer tcpdump-mini luci-app-nlbwmon"  
  
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo mkdir -p /mnt/workdir
        sudo chown $USER:$GROUPS /mnt/workdir
    - name: Download imagebuilder
      working-directory: /mnt/workdir
      run: |
        curl -O "https://downloads.openwrt.org/snapshots/targets/${{ env.BOARD }}/${{ env.SUBTARGET }}/openwrt-imagebuilder-${{ env.BOARD }}-${{ env.SUBTARGET }}.Linux-x86_64.tar.zst"
        tar xvaf openwrt-imagebuilder-${{ env.BOARD }}-${{ env.SUBTARGET }}.Linux-x86_64.tar.zst
        ln -sf /mnt/workdir/openwrt-imagebuilder-${{ env.BOARD }}-${{ env.SUBTARGET }}.Linux-x86_64 $GITHUB_WORKSPACE/openwrt
 
    # Pull the first six letters from the version.buildinfo-file for naming the release e. g. "R16767"
    - name: Download version info
      run: |
        curl -O "https://downloads.openwrt.org/snapshots/targets/${{ env.BOARD }}/${{ env.SUBTARGET }}/version.buildinfo"
        echo "OPENWRT_VERSION=$(cut -c-6 <<< cat version.buildinfo)" >> $GITHUB_ENV 
     
    - name: Include External ipk-Packages
      run: |
        wget -O packages.txt https://github.com/minax007/packages/raw/main/external-package-urls-apk.txt
        cat packages.txt | xargs wget -P /mnt/workdir/openwrt-imagebuilder-${{ env.BOARD }}-${{ env.SUBTARGET }}.Linux-x86_64/packages
    
    - name: Build the image of type 1
      id: type1
      run: |
        cd openwrt
        make image PROFILE="${{ env.PROFILE }}" PACKAGES="${{ env.PACKAGES_TYPE1 }}"
        mv bin/targets/${{ env.BOARD }}/${{ env.SUBTARGET }}/openwrt-${{ env.BOARD }}-${{ env.SUBTARGET }}-${{ env.PROFILE }}-squashfs-sysupgrade.bin OpenWrt_MiWiFi-3A_${{ env.OPENWRT_VERSION }}_sysupgrade.bin
    - name: Build the image of type 2
      id: type2
      run: |
        cd openwrt
        make image PROFILE="${{ env.PROFILE }}" PACKAGES="${{ env.PACKAGES_TYPE2 }}"
        mv bin/targets/${{ env.BOARD }}/${{ env.SUBTARGET }}/openwrt-${{ env.BOARD }}-${{ env.SUBTARGET }}-${{ env.PROFILE }}-squashfs-sysupgrade.bin OpenWrt_MiWiFi-3A_${{ env.OPENWRT_VERSION }}_LEAN_sysupgrade.bin
        
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.RELEASE }}
        release_name: OpenWrt MiWiFi-3A (${{ env.RELEASE }})
        body: |
          This release is based on OpenWrt release ${{ env.RELEASE }}.
                    
        draft: false
        prerelease: false

    - name: Upload type1 Asset
      id: upload-release-asset-type1
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: openwrt/OpenWrt_MiWiFi-3A_${{ env.RELEASE }}_sysupgrade.bin
        asset_name: OpenWrt_MiWiFi-3A_${{ env.RELEASE }}_sysupgrade.bin
        asset_content_type: application/bin

    - name: Upload type2 Asset
      id: upload-release-asset-type2
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: openwrt/OpenWrt_MiWiFi-3A_${{ env.RELEASE }}_LEAN_sysupgrade.bin
        asset_name: OpenWrt_MiWiFi-3A_${{ env.RELEASE }}_LEAN_sysupgrade.bin
        asset_content_type: application/bin
